apiVersion: v1
kind: Service
metadata:
  name: catalog-db
  labels:
    app.kubernetes.io/name: catalog-db
spec:
  ports:
  - name: "1433"
    port: 1433
    targetPort: 1433
  selector:
    app.kubernetes.io/name: catalog-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-db
  labels:
    app.kubernetes.io/name: catalog-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: catalog-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: catalog-db
    spec:
      containers:
        - name: catalog-db
          image: mcr.microsoft.com/mssql/server:2019-CU13-ubuntu-20.04
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: catalog_db_password
          volumeMounts:
            - mountPath: /var/opt/mssql
              name: catalog-db-data
      restartPolicy: Always
      volumes:
      - name: catalog-db-data
        persistentVolumeClaim:
          claimName: catalog-db-data