apiVersion: v1
kind: Service
metadata:
  name: user-db
  labels:
    app.kubernetes.io/name: user-db
spec:
  type: NodePort
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app.kubernetes.io/name: user-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  labels:
    app.kubernetes.io/name: user-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: user-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: user-db
    spec:
      containers:
        - name: user-db
          image: mysql:8.0.26
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: user-db
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: user_db_root_password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: user_db_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: user_db_password
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: user-db-data
      restartPolicy: Always
      volumes:
        - name: user-db-data
          persistentVolumeClaim:
            claimName: user-db-data