version: '3.4'

services:
  upload-service:
    build:
      context: VideoUploadService
      dockerfile: VideoUploadService/Dockerfile
    environment:
      FileStorageSettings__DiskStorePath: /data
    ports: 
      - "8080:80"
    volumes:
      - /f/tusfiles:/data
      
  webclient:
    build:
      context: webclient
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    
