# https://stackoverflow.com/questions/33478555/kubernetes-equivalent-of-env-file-in-docker
apiVersion: v1
kind: Secret
metadata:
  name: my-secrets
type: Opaque
data:
  # top_secret_secret
  jwt_secret: dG9wX3NlY3JldF9zZWNyZXQ=
  # user1
  message_queue_user: dXNlcjE=
  # password1
  message_queue_password: cGFzc3dvcmQx
  # helloworld
  user_db_root_password: aGVsbG93b3JsZA==
  # mysql-user
  user_db_user: bXlzcWwtdXNlcg==
  # mysql-password
  user_db_password: bXlzcWwtcGFzc3dvcmQ=
  # Your_password123
  catalog_db_password: WW91cl9wYXNzd29yZDEyMw==
