apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    name-label: nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - soft
    - nfsvers=3.0
    - nolock
  nfs:
    path: /f/tusfiles
    server: host.docker.internal
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: slow
  selector:
    matchLabels:
      name-label: nfs-pv