apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-db-data
  labels:
    app.kubernetes.io/name: user-db-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi