FROM openjdk:11.0.9.1-jre-slim-buster AS base
EXPOSE 8080
EXPOSE 5005
RUN mkdir /app
WORKDIR /app

FROM openjdk:11.0.9.1-jdk-buster AS build
WORKDIR /home/gradle/src
COPY gradle ./gradle
COPY gradlew .
RUN ./gradlew build || return 0
# gradle.properties
COPY build.gradle.kts settings.gradle.kts ./
# Only download dependencies
RUN ./gradlew downloadDependencies
COPY . .
# Exclude tests for faster builds, CI will run tests
RUN ./gradlew clean build -x test

FROM base AS final
COPY --from=build /home/gradle/src/build/libs/user_service-0.0.1-SNAPSHOT.jar .
CMD ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-server", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseG1GC", "-XX:MaxGCPauseMillis=100", "-XX:+UseStringDeduplication", "-jar", "user_service-0.0.1-SNAPSHOT.jar"]

