version: '3.4'

services:
  catalog-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  convert-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  upload-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  user-service:
    build:
      context: ../user_service
      dockerfile: Dockerfile_debug
    ports: 
      - "5004:80"
      - "5005:5005"