name: CatalogService

on:
  push:
    branches: [ master ]
    paths:
      - 'VideoStreaming/CatalogService/**'
      - 'VideoStreaming/MessageQueueDTOs/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'VideoStreaming/CatalogService/**'
      - 'VideoStreaming/MessageQueueDTOs/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - uses: actions/cache@v2
      with:
        path: |
          ~/.nuget/packages
          !~/.nuget/packages/unwanted
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./VideoStreaming/CatalogService
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./VideoStreaming/CatalogService
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./VideoStreaming/CatalogService
