name: .NET

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'VideoStreaming/ConvertService/**'
      - 'VideoStreaming/UploadService/**'
      - 'webclient/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'VideoStreaming/ConvertService/**'
      - 'VideoStreaming/UploadService/**'
      - 'webclient/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Change directory
      run: cd VideoStreaming
    - uses: actions/cache@v2
      with:
        path: |
          ~/.nuget/packages
          !~/.nuget/packages/unwanted
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Restore dependencies
      run: dotnet restore CatalogService
    - name: Build
      run: dotnet build CatalogService --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
