name: UserService

on:
  push:
    branches: [ master, tests ]
    paths:
      - '.github/workflows/user-service.yml'
      - 'user_service/**'
  pull_request:
    branches: [ master, tests ]
    paths:
      - '.github/workflows/user-service.yml'
      - 'user_service/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
           ~/.gradle/caches
           ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
           ${{ runner.os }}-gradle-
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./user_service
    - name: Download dependencies
      run: ./gradlew downloadDependencies
      working-directory: ./user_service
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./user_service
